version: '2'
services:
    web:
        build: ""
        ports:
            - "8000:8000"
        volumes:
            - .:/django2
        links:
            - db


    db:
        image: "postgres:9.6"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: postgres